AWSTemplateFormatVersion: "2010-09-09"
Description: Stack to create Frontend

Parameters:
  ResourcesPrefix:
    Type: String

  TaskExecutionRoleARN:
    Type: String

  ContainerName:
    Type: String

  ContainerPort:
    Type: Number

  ECRImageRepository:
    Type: String
  
  ALBDNSName:
    Type: String

  StackName:
    Type: String
    Default: frontend.yaml

  VPCId:
    Type: String

  Subnets:
    Type: String

  ALB:
    Type: String

  SecurityGroup:
    Type: String

  TargetGroupName:
    Type: String

  TargetGroupHealthCheckPath:
    Type: String
  
  ECSCluster:
    Type: String

  CloudWatchLogGroupName:
    Type: String  

  BaseTemplateURLParameter:
    Type: String

  ServiceName:  
    Type: String

  DesiredCount:  
    Type: Number

  TaskCpu:
    Type: String

  TaskMemory:
    Type: String

  ProjectName:
    Type: String 

  Environment:
    Type: String 
    
  Team:
    Type: String 

Resources:
  FrontendTaskDefinitionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${BaseTemplateURLParameter}.s3.${AWS::Region}.amazonaws.com/services/frontend/ecs-front-taskdefinition.yaml"
      Parameters:
        ECRImageRepository: !Ref ECRImageRepository
        ResourcesPrefix: !Ref ResourcesPrefix
        ContainerPort: !Ref ContainerPort
        ContainerName: !Ref ContainerName
        TaskExecutionRoleARN: !Ref TaskExecutionRoleARN
        ALBDNSName: !Ref ALBDNSName
        StackName: !Ref StackName
        CloudWatchLogGroupName: !Ref CloudWatchLogGroupName
        TaskCpu: !Ref TaskCpu
        TaskMemory: !Ref TaskMemory
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        Team: !Ref Team
  FrontendServiceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${BaseTemplateURLParameter}.s3.${AWS::Region}.amazonaws.com/services/frontend/ecs-front-service.yaml"
      Parameters:
        VPCId: !Ref VPCId
        Subnets: !Ref Subnets
        ALB: !Ref ALB
        SecurityGroup: !Ref SecurityGroup
        StackName: !Ref StackName
        ResourcesPrefix: !Ref ResourcesPrefix
        ServiceName: !Ref ServiceName
        TargetGroupName: !Ref TargetGroupName
        ContainerPort: !Ref ContainerPort
        TargetGroupHealthCheckPath: !Ref TargetGroupHealthCheckPath
        ContainerName: !Ref ContainerName
        ECSCluster: !Ref ECSCluster
        TaskDefinitionArn: !GetAtt FrontendTaskDefinitionStack.Outputs.TaskDefinitionArn
        DesiredCount: !Ref DesiredCount
        ProjectName: !Ref ProjectName
        Environment: !Ref Environment
        Team: !Ref Team