AWSTemplateFormatVersion: "2010-09-09"
Description: ECS service

Parameters:
  ResourcesPrefix:
    Type: String

  TaskExecutionRoleARN:
    Type: String

  ContainerName:
    Type: String

  ContainerPort:
    Type: Number

  ECRImageRepository:
    Type: String
  
  ALBDNSName:
    Type: String

  StackName:
    Type: String

  CloudWatchLogGroupName:
    Type: String  

  RDSInstanceEndpoint:
    Type: String

  RDSInstancePort:
    Type: Number

  DBName:
    Type: String
  
  DBSecretArn:
    Type: String

  TaskCpu:
    Type: String

  TaskMemory:
    Type: String

  ProjectName:
    Type: String 

  Environment:
    Type: String 
    
  Team:
    Type: String 

Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub "${ResourcesPrefix}-${Environment}-task"
      RequiresCompatibilities:
        - FARGATE
      Cpu: !Ref TaskCpu 
      Memory: !Ref TaskMemory
      NetworkMode: awsvpc
      ExecutionRoleArn: !Ref TaskExecutionRoleARN
      ContainerDefinitions:
        - Name: !Ref ContainerName
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRImageRepository}"
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          Essential: true
          Environment:
            - Name: DB_HOST
              Value: !Ref RDSInstanceEndpoint
            - Name: DB_PORT
              Value: !Ref RDSInstancePort
            - Name: DB_NAME
              Value: !Ref DBName
          Secrets:
            - Name: DB_USER
              ValueFrom: !Sub "${DBSecretArn}:username::"
            - Name: DB_PASSWORD
              ValueFrom: !Sub "${DBSecretArn}:password::"
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudWatchLogGroupName
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
      Tags:
        - Key: Name
          Value: !Sub "${ResourcesPrefix}-${Environment}-task"
        - Key: Stack
          Value: !Ref StackName
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Team
          Value: !Ref Team 

Outputs:
  TaskDefinitionArn:
    Description: ARN de la Task Definition
    Value: !Ref TaskDefinition


# ✅ ToDos 
# 1. Define `cpu` and `memory` values as CloudFormation parameters for flexibility.
# 2. Consider adding `HealthCheck` settings in the container definition.
# 3. Use `secretsManager` for environment variables instead of hardcoding sensitive values.
# 4. Ensure `awslogs-group` exists before deployment to avoid log stream issues.