AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an SNS topic with an email subscription

Parameters:
  EmailEndpoint:
    Type: String

  StackName:
    Type: String
    Default: sns.yaml

  ResourcesPrefix:
    Type: String

  ProjectName:
    Type: String 

  Environment:
    Type: String 
    
  Team:
    Type: String 

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub "${ResourcesPrefix}-${Environment}-sns"
      TopicName: !Sub "${ResourcesPrefix}-${Environment}-sns"
      Tags:
        - Key: Name
          Value: !Sub "${ResourcesPrefix}-${Environment}-sns"
        - Key: Stack
          Value: !Ref StackName
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Team
          Value: !Ref Team

  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: !Ref EmailEndpoint
      TopicArn: !Ref SNSTopic

Outputs:
  SNSTopicArn:
    Description: ARN of the created SNS topic
    Value: !Ref SNSTopic