AWSTemplateFormatVersion: "2010-09-09"
Description: Root stack 

Parameters:
  BaseTemplateURLParameter:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/BaseTemplateS3URL
    Description: The base URL for the S3 bucket where the CloudFormation templates are stored

  VPCId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/VPCId
    Description: The ID of the existing VPC

  ResourcesPrefix:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/ResourcesPrefix
    Description: Prefix used for naming AWS resources and tagging

  DBUsername:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/DBUsername
    Description: The username for the database instance

  DBInstanceClass:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/DBInstanceClass
    Description: The instance class for the database

  DBEngine:
    Type: String
    Default: postgres
    Description: The database engine to use
  
  DBBackupRetentionPeriod:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/DBBackupRetentionPeriod
    Description: Number of days to retain automatic backups

  DBPreferredBackupWindow:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/DBPreferredBackupWindow
    Description: Time window for automated backups (UTC time)

  DBPreferredMaintenanceWindow:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/DBPreferredMaintenanceWindow
    Description: Time window for RDS maintenance (UTC time)

  PrivateSubnets:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/PrivateSubnets
    Description: List of private subnet IDs, separated by commas

  RouteTables:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/RouteTables
    Description: List of route table IDs, separated by commas

  PublicSubnets:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/PublicSubnets
    Description: List of public subnet IDs, separated by commas

  CWLogGroupRetentionInDays:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/CWLogGroupRetentionInDays
    Description: Number of days to retain logs in the CloudWatch LogGroup

  FrontendTargetGroupName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/FrontendTargetGroupName
    Description: The name of the Target Group for the frontend service

  FrontendContainerPort:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/FrontendContainerPort
    Description: The port on which the frontend container listens

  TargetGroupHealthCheckPath:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/TargetGroupHealthCheckPath
    Description: The health check path for the frontend Target Group
  
  FrontendContainerName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/FrontendContainerName
    Description: The name of the frontend container in ECS

  FrontendImageRepository:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/FrontendImageRepository
    Description: ECR image repository for the frontend

  ServiceName:  
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/ServiceName
    Description: Name of the ECS service (e.g., frontend, backend)

  DesiredCount:  
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/DesiredCount
    Description: Number of ECS tasks to run

  BackendTargetGroupName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/BackendTargetGroupName
    Description: The name of the Target Group for the backend service

  BackendContainerPort:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/BackendContainerPort
    Description: The port on which the backend container listens

  BackendContainerName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/BackendContainerName
    Description: The name of the backend container in ECS

  BackendImageRepository:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/BackendImageRepository
    Description: ECR image repository for the backend

  MLImageRepository:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/MLImageRepository
    Description: ECR image repository for the ML model

  HealthCheckImageRepository:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/HealthCheckImageRepository
    Description: ECR image repository for the health check

  BackendServiceName:  
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/BackendServiceName
    Description: Name of the ECS service (e.g., frontend, backend)

  MLTargetGroupName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/MLTargetGroupName
    Description: The name of the Target Group for the ML service
  
  MLContainerPort:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/MLContainerPort
    Description: The port on which the ML container listens

  MLServiceName:  
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/MLServiceName
    Description: Name of the ECS service (e.g., frontend, backend)

  MLContainerName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/MLContainerName
    Description: The name of the ML container in ECS

  ScheduleExpression:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vwm-infrastructure/ScheduleExpression
    Description: The schedule expression for the EventBridge rule

Resources:
  SGStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${BaseTemplateURLParameter}.s3.${AWS::Region}.amazonaws.com/network/sg.yaml"
      Parameters:
        VPCId: !Ref VPCId
        ResourcesPrefix: !Ref ResourcesPrefix