AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket

Parameters:
  BucketName:
    Type: String
    
  StackName:
    Type: String
    Default: s3.yaml

  ResourcesPrefix:
    Type: String

  BucketVersioningConfiguration:
    Type: String

  ProjectName:
    Type: String 

  Environment:
    Type: String 
    
  Team:
    Type: String 

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ResourcesPrefix}-${Environment}-${BucketName}"
      LifecycleConfiguration:
        Rules:
          - Id: MoveToIntelligentTiering
            Status: Enabled
            Transitions:
              - StorageClass: INTELLIGENT_TIERING
                TransitionInDays: 30
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: !Ref BucketVersioningConfiguration
      Tags:
          - Key: Name
            Value: !Sub "${ResourcesPrefix}-${Environment}-s3"
          - Key: Stack
            Value: !Ref StackName
          - Key: Project
            Value: !Ref ProjectName
          - Key: Environment
            Value: !Ref Environment
          - Key: Team
            Value: !Ref Team

Outputs:
  S3BucketName:
    Description: "Name of the created S3 bucket"
    Value: !Ref S3Bucket

# Open Questions:
  # Object lock will be enabled?