AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  BucketName:
    Type: String
    Description: "Name of the S3 bucket to be created"
    
  StackName:
    Type: String
    Default: s3.yaml

  ResourcesPrefix:
    Type: String

  BucketVersioningCongiguration:
    Type: String
    Default: Enabled


Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: !Ref BucketVersioningCongiguration
      Tags:
          - Key: Name
            Value: !Sub "${ResourcesPrefix}-s3"
          - Key: Stack
            Value: !Ref StackName
Outputs:
  BucketName:
    Description: "Name of the S3 bucket created"
    Value: !Ref S3Bucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"

# 🔥 TODO: 
# Add a bucket policy to restrict access to the bucket to a specific IAM role
# Add versioning
# Add object lock
# Add lifecycle policy