AWSTemplateFormatVersion: "2010-09-09"
Description: Stack to create ECS cluster

Parameters:
  StackName:
    Type: String
    Default: ecs-cluster.yaml

  ResourcesPrefix:
    Type: String

  ProjectName:
    Type: String
    Default: WVM-Advanced-Logistics-Analytics

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${ResourcesPrefix}-ecs-cluster"
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
      Tags:
        - Key: Name
          Value: !Sub "${ResourcesPrefix}-ecs-cluster"
        - Key: Stack
          Value: !Ref StackName
        - Key: Project
          Value: !Ref ProjectName
Outputs:
  ECSCluster:
    Description: ECS cluster
    Value: !Ref ECSCluster