AWSTemplateFormatVersion: "2010-09-09"
Description: Stack to create Network Load Balancer in front of Application Load Balancer

Parameters:
  VPCId:
    Default: "vpc-12345678"
    Type: String
    Description: "VPC ID where the resources will be created"

  Subnets:
    Default: "subnet-037029409ebf2e40a,subnet-02d3b1f7781083329,subnet-04b8975560e504362,subnet-0bc409e74d3daace3,subnet-0f84440d859dff00a,subnet-0c2415ce936583b0f"
    Type: String
    Description: "Comma-separated list of subnet IDs for the NLB"

  ALBArn:
    Type: String
    Default: "arn:aws:elasticloadbalancing:us-east-1:302672446683:loadbalancer/app/vwm-alb/90ad9b35081cb8a8"
    Description: "ARN of the existing Application Load Balancer"

  StackName:
    Type: String
    Default: "alb.yaml"
    Description: "Stack name for tagging purposes"

  ResourcesPrefix:
    Type: String
    Description: "Prefix to be used for naming resources"

Resources:
  NLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${ResourcesPrefix}-nlb"
      Scheme: internet-facing
      Subnets: !Split [",", !Ref Subnets]
      Type: network
      Tags:
        - Key: Name
          Value: !Sub "${ResourcesPrefix}-nlb"
        - Key: Stack
          Value: !Ref StackName

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${ResourcesPrefix}-alb-tg"
      VpcId: !Ref VPCId
      Protocol: TCP
      Port: 80
      TargetType: alb
      LoadBalancerArns:
        - !Ref ALBArn  
      Tags:
        - Key: Name
          Value: !Sub "${ResourcesPrefix}-alb-tg"
        - Key: Stack
          Value: !Ref StackName

  NLBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref NLB
      Port: 80
      Protocol: TCP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup

Outputs:
  NLB:
    Description: Logical ID of the NLB resource
    Value: !Ref NLB

  NLBDNSName:
    Description: DNS Name of the NLB resource
    Value: !GetAtt NLB.DNSName


#Note:
# 1. The targets has to be registered manually to the target group due to the limitation of the CloudFormation