AWSTemplateFormatVersion: "2010-09-09"
Description: Stack to create Network Load Balancer in front of Application Load Balancer

Parameters:
  VPCId:
    Type: String

  Subnets:
    Type: String

  ALBArn:
    Type: String

  StackName:
    Type: String
    Default: "alb.yaml"

  ResourcesPrefix:
    Type: String

  ProjectName:
    Type: String 

  Environment:
    Type: String 
    
  Team:
    Type: String 

Resources:
  NLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${ResourcesPrefix}-${Environment}-nlb"
      Scheme: internet-facing
      Subnets: !Split [",", !Ref Subnets]
      Type: network
      Tags:
        - Key: Name
          Value: !Sub "${ResourcesPrefix}-${Environment}-nlb"
        - Key: Stack
          Value: !Ref StackName
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Team
          Value: !Ref Team

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${ResourcesPrefix}-${Environment}-alb-tg"
      VpcId: !Ref VPCId
      Protocol: TCP
      Port: 80
      TargetType: alb
      LoadBalancerArns:
        - !Ref ALBArn  
      Tags:
        - Key: Name
          Value: !Sub "${ResourcesPrefix}-${Environment}-alb-tg"
        - Key: Stack
          Value: !Ref StackName
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Team
          Value: !Ref Team

  NLBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref NLB
      Port: 80
      Protocol: TCP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
        - Key: Environment
          Value: !Ref Environment
        - Key: Team
          Value: !Ref Team

Outputs:
  NLB:
    Description: Logical ID of the NLB resource
    Value: !Ref NLB

  NLBDNSName:
    Description: DNS Name of the NLB resource
    Value: !GetAtt NLB.DNSName


#Note:
# 1. The targets has to be registered manually to the target group due to the limitation of the CloudFormation
# 2. There is a listerner with port 80 if we configure tls we have to add 443 instead of 80