name: Build and Push to ECR

on:
  workflow_run:
    workflows: 
      - "Python Backend Check"
      - "Vue Frontend Check"
    types:
      - completed
  push:
    tags:
      - '*' # Trigger on every tag push

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      # Step 4: Build and Push Frontend
      - name: Build and Push Frontend
        run: |
          docker build -t vwm-advanced-logistics-analytics-infrastructure-frontend demo/frontend/vue-you-did-it/
          docker tag vwm-advanced-logistics-analytics-infrastructure-frontend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/vwm-advanced-logistics-analytics-infrastructure-frontend:${{ github.ref_name }}
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/vwm-advanced-logistics-analytics-infrastructure-frontend:${{ github.ref_name }}

      # Step 5: Build and Push Backend
      - name: Build and Push Backend
        run: |
          docker build -t vwm-advanced-logistics-analytics-infrastructure-backend demo/backend/
          docker tag vwm-advanced-logistics-analytics-infrastructure-backend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/vwm-advanced-logistics-analytics-infrastructure-backend:${{ github.ref_name }}
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/vwm-advanced-logistics-analytics-infrastructure-backend:${{ github.ref_name }}

      # Step 6: Scan Frontend Image in ECR
      - name: Scan Frontend Image
        run: |
          aws ecr start-image-scan \
            --repository-name vwm-advanced-logistics-analytics-infrastructure-frontend \
            --image-id imageTag=${{ github.ref_name }}

      # Step 7: Scan Backend Image in ECR
      - name: Scan Backend Image
        run: |
          aws ecr start-image-scan \
            --repository-name vwm-advanced-logistics-analytics-infrastructure-backend \
            --image-id imageTag=${{ github.ref_name }}

      # Step 8: Wait and Describe Scan Results for Frontend
      - name: Get Scan Results for Frontend
        run: |
          aws ecr describe-image-scan-findings \
            --repository-name vwm-advanced-logistics-analytics-infrastructure-frontend \
            --image-id imageTag=${{ github.ref_name }}

      # Step 9: Wait and Describe Scan Results for Backend
      - name: Get Scan Results for Backend
        run: |
          aws ecr describe-image-scan-findings \
            --repository-name vwm-advanced-logistics-analytics-infrastructure-backend \
            --image-id imageTag=${{ github.ref_name }}
