name: Build and Push to ECR

on:
  workflow_run:
    workflows: 
      - "Python Backend Check"
      - "Vue Frontend Check"
    types:
      - completed
  push:
    tags:
      - '*' # Trigger on every tag push

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      # Step 4: Build and Push Frontend
      - name: Build and Push Frontend
        run: |
          docker build -t vwm-advanced-logistics-analytics-infrastructure-frontend demo/frontend/vue-you-did-it/
          docker tag vwm-advanced-logistics-analytics-infrastructure-frontend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/vwm-advanced-logistics-analytics-infrastructure-frontend:${{ github.ref_name }}
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/vwm-advanced-logistics-analytics-infrastructure-frontend:${{ github.ref_name }}

      # Step 5: Build and Push Backend
      - name: Build and Push Backend
        run: |
          docker build -t vwm-advanced-logistics-analytics-infrastructure-backend demo/backend/
          docker tag vwm-advanced-logistics-analytics-infrastructure-backend:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/vwm-advanced-logistics-analytics-infrastructure-backend:${{ github.ref_name }}
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/vwm-advanced-logistics-analytics-infrastructure-backend:${{ github.ref_name }}

      # Step 6: Scan Frontend Image and Wait
      - name: Scan and Wait for Frontend Image
        run: |
          aws ecr start-image-scan --repository-name vwm-advanced-logistics-analytics-infrastructure-frontend --image-id imageTag=${{ github.ref_name }}
          for i in {1..30}; do  # Hasta 30 intentos (5 minutos en total)
            status=$(aws ecr describe-image-scan-findings \
              --repository-name vwm-advanced-logistics-analytics-infrastructure-frontend \
              --image-id imageTag=${{ github.ref_name }} \
              --query "imageScanStatus.status" --output text 2>/dev/null || echo "ERROR")
            
            if [[ "$status" == "COMPLETE" ]]; then
              echo "Frontend image scan completed."
              break
            elif [[ "$status" == "FAILED" ]]; then
              echo "Frontend image scan failed."
              exit 1
            elif [[ "$status" == "ERROR" ]]; then
              echo "Error retrieving scan status. Retrying..."
            else
              echo "Frontend image scan in progress. Retrying in 10 seconds..."
            fi
            sleep 10
          done
          
          if [[ "$status" != "COMPLETE" ]]; then
            echo "Frontend image scan did not complete within the expected time."
            exit 1
          fi

          aws ecr describe-image-scan-findings \
            --repository-name vwm-advanced-logistics-analytics-infrastructure-frontend \
            --image-id imageTag=${{ github.ref_name }}

      # Step 7: Scan Backend Image and Wait
      - name: Scan and Wait for Backend Image
        run: |
          aws ecr start-image-scan --repository-name vwm-advanced-logistics-analytics-infrastructure-backend --image-id imageTag=${{ github.ref_name }}
          for i in {1..30}; do  # Hasta 30 intentos (5 minutos en total)
            status=$(aws ecr describe-image-scan-findings \
              --repository-name vwm-advanced-logistics-analytics-infrastructure-backend \
              --image-id imageTag=${{ github.ref_name }} \
              --query "imageScanStatus.status" --output text 2>/dev/null || echo "ERROR")
            
            if [[ "$status" == "COMPLETE" ]]; then
              echo "Backend image scan completed."
              break
            elif [[ "$status" == "FAILED" ]]; then
              echo "Backend image scan failed."
              exit 1
            elif [[ "$status" == "ERROR" ]]; then
              echo "Error retrieving scan status. Retrying..."
            else
              echo "Backend image scan in progress. Retrying in 10 seconds..."
            fi
            sleep 10
          done
          
          if [[ "$status" != "COMPLETE" ]]; then
            echo "Backend image scan did not complete within the expected time."
            exit 1
          fi

          aws ecr describe-image-scan-findings \
            --repository-name vwm-advanced-logistics-analytics-infrastructure-backend \
            --image-id imageTag=${{ github.ref_name }}
