name: Upload to S3

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the 'main' branch

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Update with your AWS region

    - name: Set up permissions for the script
      run: chmod +x aws/scripts/upload-to-s3.sh

    - name: Upload files to S3
      env:
        S3_BUCKET: stack-vwm-advanced-logistics-analytics-infrastructure
      run: aws/scripts/upload-to-s3.sh
